---
- name: Init chatbot server

  hosts: localhost

  vars_files:

  vars:
    - gitDir: '/var/www/git/'
    - appsDir: '/var/www'
    - backDir: 'chatbot-back'
    - botDir: 'chatbot-template'
    - frontDir: 'chatbot-front'
    - webchatDir: 'webchat'

  tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: 'yes'
        update_cache: 'yes'

    - name: Ansible galaxy install elastic.beats role
      shell: 'ansible-galaxy install elastic.beats,v7.10.1'

    - name: Set right rights on www directory
      file:
        path: '{{appsDir}}'
        group: www-data
        mode: '774'
        recurse: yes

    - name: Copy chatbot-back
      synchronize:
        src: '{{ gitDir }}/{{ backDir }}/'
        dest: '{{ appsDir }}/{{ backDir }}'
        rsync_opts:
          - '--exclude=mediatheque/'
          - '--exclude=historic/'
      when: updateBack

    - name: Copy env-file
      copy:
        src: '{{ gitDir }}/.env'
        dest: '{{ appsDir }}/{{ backDir }}/.env'
      when: updateBack

    - name: Copy chatbot-front
      synchronize:
        src: '{{ gitDir }}/{{ frontDir }}/dist/{{ frontDir }}/'
        dest: '{{ appsDir }}/{{ frontDir }}'
        delete: yes
      when: updateFront

    - name: Copy webchat
      synchronize:
        src: '{{ gitDir }}/{{ frontDir }}/dist/{{ webchatDir }}/'
        dest: '{{ appsDir }}/{{ webchatDir }}'
        delete: yes
      when: updateFront

    - name: copy the nginx config file
      copy:
        src: '{{ gitDir }}/nginx.conf'
        dest: '/etc/nginx/nginx.conf'
      become: yes
      when: updateFront

    - name: copy the nginx site config file
      copy:
        src: '{{ gitDir }}/nginx_conf.cfg'
        dest: '/etc/nginx/sites-available/{{ frontDir }}.cfg'
      when: updateFront

    - name: add server name to the nginx site config file
      lineinfile:
        path: '/etc/nginx/sites-available/{{ frontDir }}.cfg'
        insertbefore : '^    location / {'
        line: '    server_name  {{ botDomain }};'
      when: updateFront and botDomain

    - name: create symlink
      file:
        src: '/etc/nginx/sites-available/{{ frontDir }}.cfg'
        dest: '/etc/nginx/sites-enabled/default'
        state: link
      when: updateFront

    - name: restart nginx
      service:
        name: nginx
        state: restarted
      when: updateFront

    - name: Install SSL certificate
      command:
        cmd: 'certbot --nginx -d {{ botDomain }} -n --redirect --agree-tos -m vincent.laine@beta.gouv.fr'
      when: updateFront and botDomain

    - name: Install RASA version
      pip:
        executable: pip3
        name:
          - rasa>=2.1.0,<3.0
          - psycopg2-binary
      when: updateRasa

    - name: Copy chatbot-template
      synchronize:
        src: '{{ gitDir }}/{{ botDir }}/'
        dest: '{{ appsDir }}/{{ botDir }}'
        rsync_opts:
          - '--exclude=models/'
      when: updateRasa

    - name: npm install chatbot-back
      command:
        cmd: sudo npm install --build-from-source
        chdir: '{{ appsDir }}/{{ backDir }}'
      when: updateBack

    - name: npm build chatbot-back
      command:
        cmd: 'npm run build'
        chdir: '{{ appsDir }}/{{ backDir }}'
      when: updateBack

    - name: npm copy env file
      command:
        cmd: 'npm run copy'
        chdir: '{{ appsDir }}/{{ backDir }}'
      when: updateBack

    - name: Copy endpoints.yml rasa file
      copy:
        src: '{{ appsDir }}/{{ botDir }}/endpoints.example.yml'
        dest: '{{ appsDir }}/{{ botDir }}/endpoints.yml'
        remote_src: yes
      when: updateRasa

    - name: Update endpoints.yml rasa file
      lineinfile:
        path: '{{ appsDir }}/{{ botDir }}/endpoints.yml'
        regexp: '^  password:'
        line: '  password: "{{ DB_PASSWORD }}"'
      when: updateRasa

    - name: Train rasa
      command:
        chdir: '{{ appsDir }}/{{ botDir }}/'
        cmd: 'rasa train --num-threads 8'
      when: updateRasa

    - name: Stop rasa chatbot
      command: 'pkill screen'
      ignore_errors: true
      when: updateRasa

    - name: Start rasa chatbot
      command:
        chdir: '{{ appsDir }}/{{ botDir }}/'
        cmd: 'screen -S rasa -dmS rasa run -m models --enable-api --log-file out.log --cors "*" --debug'
      when: updateRasa

    - name: Start rasa action server
      command:
        chdir: '{{ appsDir }}/{{ botDir }}/'
        cmd: 'screen -S rasa-action -dmS rasa run actions'
      when: updateRasa

    - name: copy rc.local file to restart bot on boot
      copy:
        src: '{{ gitDir }}/rc.local'
        dest: '/etc/rc.local'
      when: updateRasa

    - name: Set right rights on rc.local file
      when: updateRasa
      file:
        path: '/etc/rc.local'
        mode: '755'
